# BEAT SCHEMA
type Beat @model {
  id: ID!
  title: String!
  owner: Owner!
  thumbnail: S3Object
  audio: BeatFile!
  genre: Genre!
  tags: Tags
  public: Boolean!
  price: Price!
  bpm: Int!
  schedule: String
  split: Split
  free: Boolean
}

type S3Object {
  region: String!
  bucket: String!
  key: String!
}

type BeatFile {
  mp3: S3Object!
  wav: S3Object
  zip: S3Object
}

type Price {
  MP3Price: Int
  WAVPrice: Int
  TrackoutPrice: Int
  UnlimitedPrice: Int
  ExclusivePrice: Int
}

type Genre {
  genre1: String!
  genre2: String!
  genre3: String!
}

type Tags {
  tag1: String!
  tag2: String!
  tag3: String!
}

type Owner {
  ownerId: String!
  ownerUsername: String!
}

type Collaborator {
  email: String!
  percentage: Int!
}

type Split {
  split1: Collaborator!
  split2: Collaborator
  split3: Collaborator
  split4: Collaborator
}

# MESSAGES SCHEMA
type Message {
  id: ID!,
  senderId: String!,
  senderUsername: String!,
  recieverId: String!,
  recieverUsername: String!,
  messageBody: String!,
}